"""Add audit fields to users model

Revision ID: 195b59ea51e0
Revises: 3ceedca8385f
Create Date: 2025-12-13 16:16:12.319939
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "195b59ea51e0"
down_revision = '3ceedca8385f'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_date')
    op.drop_column('users', 'created_date')
    # ### end Alembic commands ###
