"""Add user_status to users

Revision ID: 2e7c22c73159
Revises: bb18a14fde98
Create Date: 2025-12-11 21:47:35.249414
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "2e7c22c73159"
down_revision = 'bb18a14fde98'
branch_labels = None
depends_on = None

user_status_enum = sa.Enum(
    "pending",
    "active",
    "inactive",
    name="userstatus"
)

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    user_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('user_status', user_status_enum, server_default="pending", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_status')
    user_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
