"""add password_updated_at to users

Revision ID: 45b4988139f0
Revises: 195b59ea51e0
Create Date: 2025-12-14 23:01:43.579993
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "45b4988139f0"
down_revision = '195b59ea51e0'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_updated_at')
    # ### end Alembic commands ###
