"""user table update

Revision ID: 6a5424a02bc0
Revises: 19e4c227ac6e
Create Date: 2025-11-25 21:21:21.118905
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "6a5424a02bc0"
down_revision = '19e4c227ac6e'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
