"""add audit fields to product and roles

Revision ID: 83155398b87c
Revises: ab1c2e89ca4f
Create Date: 2025-12-21 00:38:15.248555
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "83155398b87c"
down_revision = 'ab1c2e89ca4f'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'categories', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('permissions', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('permissions', sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('permissions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('permissions', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'permissions', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'permissions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('roles', sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'roles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'created_by')
    op.drop_column('roles', 'updated_date')
    op.drop_column('roles', 'created_date')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'updated_date')
    op.drop_column('products', 'created_date')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'updated_by')
    op.drop_column('permissions', 'created_by')
    op.drop_column('permissions', 'updated_date')
    op.drop_column('permissions', 'created_date')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'updated_by')
    op.drop_column('categories', 'created_by')
    op.drop_column('categories', 'updated_date')
    op.drop_column('categories', 'created_date')
    # ### end Alembic commands ###
