"""add relationship

Revision ID: a128ef41961b
Revises: a68c1429da8b
Create Date: 2025-11-28 19:43:10.658245
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "a128ef41961b"
down_revision = 'a68c1429da8b'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
