"""user table phone field modify

Revision ID: a68c1429da8b
Revises: 9c15b331dd70
Create Date: 2025-11-27 20:17:50.166269
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "a68c1429da8b"
down_revision = '9c15b331dd70'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
