"""add document table

Revision ID: ab1c2e89ca4f
Revises: 45b4988139f0
Create Date: 2025-12-19 19:51:11.090150
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "ab1c2e89ca4f"
down_revision = '45b4988139f0'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('file_identifier', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('invoice', 'order_summary', name='document_type'), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='document_status'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_file_identifier'), 'documents', ['file_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_identifier'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
