"""modify relationship

Revision ID: bb18a14fde98
Revises: a128ef41961b
Create Date: 2025-11-28 22:59:53.256745
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = "bb18a14fde98"
down_revision = 'a128ef41961b'
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
